# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 268c54c3fbb7c18b1f509ccfc9ed1d6bd06854610e11de439de71ba76bef92ab0ca327ff95c2be63cb777ef22115aaedeec0f909024900380d0c253cc1ab1d5a

test:
  secret_key_base: 0082cabf0c797f70851fb26f4e14c90f30a9fdffc51ed1d1f7b2d02f5203390d13f96291d7f63c7e90c4f22ca36f664b096725baff886b7f76f12eec1270411d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
